# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-20 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('graduation', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('alumni', models.CharField(max_length=200)),
            ],
        ),
    ]
