# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-10 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='alumni',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='graduation',
            field=models.DateField(),
        ),
    ]
